### ISSUE TITLE
Using Masked Marginal Score for ESM-2 as a Scoring Method

### ISSUE THREAD

**Issue by Amelie-Schreiber** [NREL/EvoProtGrad#2]
In the paper [Language models enable zero-shot prediction of the effects of mutations on protein function](https://www.biorxiv.org/content/10.1101/2021.07.09.450648v2) the ESM folks introduce the "Masked Marginal Scoring" method to compute effects of mutations on function and show that it performs significantly better than the Log Likelihood Ratio (LLR) method. If I am not mistaken, LLR is used for EvoProtGrad currently. Could the code from the [ESM github](https://github.com/facebookresearch/esm/tree/main/examples/variant-prediction) (where they use ESM-1v) be adapted to ESM-2 and used in EvoProtGrad as a scoring method? In particular, could the masked marginal scoring method [found here](https://github.com/facebookresearch/esm/blob/main/examples/variant-prediction/predict.py) be modified to work with ESM-2 and used in EvoProtGrad as the scoring method? The masked marginal score is defined as 

$$ \sum_{i \in M} \log p(x_i = x_i^{mt} | x_{-M}) - \log p(x_i = x_i^{wt} | x_{-M}) $$

in the paper above, in Appendix A at the bottom of page 18, where $-M$ denotes the sequence with masking at all positions in $M$, where mutations occur. That is they introduce masks at the mutated positions (all at once) and compute the score for a mutation by considering its probability relative to the wildtype amino acid. This might significantly improve the scoring and could be a nice alternative scoring strategy.

**Comment by pemami4911** [comment]
Hi, this could definitely be supported in EvoProtGrad with some minor modifications to the code in the HuggingFaceExpert class.

The masked marginal score uses the masked mutated protein sequence as input to the protein language model (PLM) and uses the (unmasked) mutations to compute the score. This could be supported by extending this `__call__` function https://github.com/NREL/EvoProtGrad/blob/fda1d39d2106c252cb529400c0cdd790ac7b62df/evo_prot_grad/experts/base_experts.py#L117 to support passing auxiliary information about what the mutations are at the masked locations in the input (e.g., passing the the unmasked sequence). 

Allowing the HuggingFaceExpert to have its score function be selected in an argument in the constructor seems reasonable as well, that way the `__call__` function can select between different score functions on the fly.

**Comment by Amelie-Schreiber** [comment]
Would you be up for working on this with me? If so, what is the best way to get in touch?

**Comment by pemami4911** [comment]
Flexible variant scoring has been added in the latest v0.2 release (at long last)! https://github.com/NREL/EvoProtGrad/releases/tag/v0.2.
